name: LLDASATest

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: >-
            cmake
          
      - name: checkout
        uses: actions/checkout@v2          

      - name: test cmake generators
        shell: msys2 {0}
        run: |
          cd  C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/
          ls
          cmake -G "Visual Studio 17 2022 Win32"
          

      - name: test ASA switch
        id: testASA
        run: |
          ld.lld --version
          ld.lld --add-stdcall-alias
