name: LLDASATest

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          install: >-
            cmake
          
      - name: checkout
        uses: actions/checkout@v2          

      - name: test cmake generators
        shell: msys2 {0}
        run: |
          cd  "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x86/"
          ls 
          cd 'C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x86/'
          ls

      - name: test ASA switch
        id: testASA
        shell: pwsh
        run: |
          echo $env:PATH
          ld.lld --version
          ld.lld --add-stdcall-alias
