name: LLDASATest

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: >-
            wget
            git
            unzip
          
      - name: checkout
        uses: actions/checkout@v2          

      - name: test ASA switch
        id: testASA
        shell: msys2 {0}
        run: |
          wget -q https://github.com/mstorsjo/llvm-mingw/releases/download/20240619/llvm-mingw-20240619-ucrt-i686.zip
          unzip -q llvm-mingw-20240619-ucrt-i686.zip
          cd llvm-mingw-20240619-ucrt-i686/bin/
          ls
